name: Code and Link Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint
        run: htmlhint index.html

      - name: Run ESLint
        run: npx eslint app.js || true

      - name: Run Stylelint
        run: npx stylelint style.css || true

      - name: Check for broken links
        run: npx linkinator . --skip 'https://www.linkedin.com/*'

      - name: Check for missing media files (HTML, CSS, JS)
        run: |
          # Check HTML files for media references
          MEDIA_FILES=$(grep -E -o "src=\"[^\"]*\.(png|ico|mp4)\"" index.html | sed -E "s/src=\"(.*)\"/\1/" | sort -u)
          echo "HTML Media Files: $MEDIA_FILES"
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

          # Check CSS files for background images and media references
          MEDIA_FILES=$(grep -E -o "url\([^\)]*\.(png|ico|mp4)\)" style.css | sed -E "s/url\([\"']?(.*)[\"']?\)/\1/" | sort -u)
          echo "CSS Media Files: $MEDIA_FILES"
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

          # Check JS files for media file references
          MEDIA_FILES=$(grep -E -o "([\"'])[^\"']*\.(png|ico|mp4)\1" app.js | sed -E "s/[\"']//g" | sort -u)
          echo "JS Media Files: $MEDIA_FILES"
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

      - name: Success message
        run: echo "All checks passed!"