name: Code and Link Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install eslint @eslint/js htmlhint csslint linkinator

      - name: Create ESLint config
        run: |
          echo 'import js from "@eslint/js";

          export default [
            js.configs.recommended,
            {
              languageOptions: {
                globals: {
                  document: "readonly",
                  window: "readonly",
                  setInterval: "readonly",
                  clearInterval: "readonly",
                },
              },
              rules: {
                "no-unused-vars": "warn",
                "no-console": "off"
              },
            }
          ];' > $GITHUB_WORKSPACE/eslint.config.mjs

      - name: Verify ESLint config exists
        run: ls -lah $GITHUB_WORKSPACE

      - name: Run ESLint
        run: eslint . --config eslint.config.mjs .

      - name: Run HTMLHint
        run: |
          htmlhint index.html

      - name: Run CSSLint
        run: |
          if [ -s style.css ]; then
            csslint style.css
          else
            echo "style.css is empty or missing!"
          fi

      - name: Check for missing media files (HTML, CSS, JS)
        run: |
          # Check HTML files for media references
          MEDIA_FILES=$(grep -E -o "src=\"[^\"]*\.(png|ico|mp4)\"" index.html | sed -E "s/src=\"(.*)\"/\1/" | sort -u)
          echo "HTML Media Files: $MEDIA_FILES"  # Debug output
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

          # Check CSS files for background images and media references
          MEDIA_FILES=$(grep -E -o "url\([^\)]*\.(png|ico|mp4)\)" style.css | sed -E "s/url\([\"']?(.*)[\"']?\)/\1/" | sort -u)
          echo "CSS Media Files: $MEDIA_FILES"  # Debug output
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

          # Check JS files for media file references (in img src, background images, etc.)
          MEDIA_FILES=$(grep -E -o "([\"'])[^\"']*\.(png|ico|mp4)\1" app.js | sed -E "s/[\"']//g" | sort -u)
          echo "JS Media Files: $MEDIA_FILES"  # Debug output
          for file in $MEDIA_FILES; do
            if [ ! -f "$GITHUB_WORKSPACE/$file" ]; then
              echo "Missing file: $file"
              exit 1
            fi
          done

      - name: Success message
        run: echo "All checks passed!"